### PR TITLE
Gestion routes API avec le frontend + correction de bugs

### LINKED ISSUE #28: Link reminder and medication backend
The frontend for the reminder and the medication needs to interact with the database to create modify and remove medication and reminders.

### PR DESCRIPTION
**Pull request by Actarus35**
Fix #28, #30

### CODE REVIEW

File: pill_mate/frontend/src/components/PopUpStock.tsx [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+                <div className="input-select">
+                    <input
+                        type="number"
+                        min={0}
+                        required= {true}
+                        value={quantity}
+                        onChange={(e) => setQuantity(parseInt(e.target.value))}
+                    />
+                    <select required= {true} onChange={(e) => setUnit(parseInt(e.target.value))}>
+                        <option value={MedicationUnit.UNIT}>Unit, no unit</option>
```
Comment (floflo0) [inline pill_mate/frontend/src/components/PopUpStock.tsx:84]: We need to translate it in french.

File: pill_mate/frontend/src/models/Medication/Medication.ts [hunk 2]
```diff
@@ -0,0 +1,10 @@
+import { MedicationUnit } from './MedicationUnit';
+
+export interface Medication {
+    id: number;
+    name: string;
+    indication: string;
```
Comment (floflo0) [inline pill_mate/frontend/src/models/Medication/Medication.ts:6]: indication may be null

File: pill_mate/frontend/src/services/medicationServices.ts [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+    return await apiService<Medication>({
+        method: 'POST',
+        body: newMedication,
+        route: '/medication',
+    });
+};
+
+export const modifyMedicationAPI = async (
+    id: number,
+    oldmedication: PatchMedication,
```
Comment (floflo0) [inline pill_mate/frontend/src/services/medicationServices.ts:19]: The name of this variable seems weird

File: pill_mate/frontend/src/services/reminderServices.ts [hunk 4]
```diff
@@ -0,0 +1,26 @@
...
+    return await apiService<Reminder>({ method: 'POST', body: newReminder, route: '/reminder/' });
+};
+
+export const deleteReminderAPI = async (id: number): Promise<void> => {
+    apiService<void>({ method: 'DELETE', route: `/reminder/${id}` });
+};
+
+export const modifyReminderAPI = async (
+    id: number,
+    oldreminder: PatchReminder,
```
Comment (floflo0) [inline pill_mate/frontend/src/services/reminderServices.ts:19]: Same, here, it's not the old value

**Review by floflo0 — CHANGES_REQUESTED** [review]
